### ISSUE TITLE
Sanitizer reporting out-of-bounds

### ISSUE THREAD

**Issue by samansmink** [cwida/fsst#9]
There seems the be an out-of-bounds error happening in https://github.com/cwida/fsst/blob/master/libfsst.cpp#L394. It triggers the sanitizer when compressing strings over 512 characters. In this case the unaligned load will read past the end of buf[512]. It still works fine, but does throw a sanitizer error in DuckDB CI. 

For null-terminated strings I'm not sure I understand how this code would prevent out-of-bounds access to user provided string buffers? 

For DuckDB we could work around it by simply increasing the buf size by 8 to stop the sanitizer from complaining. Because we don't use zero terminated strings, fsst would always copy here anyway and place the termination byte at buf[511].

**Comment by peterboncz** [comment]
I think you are correct, this can read past the end. It will not lead to incorrect results because of the terminator guaranteeing that you do not match a symbol that goes past the end (the terminator does not occur in any symbol).  But it could cause a segmentation violation, though that is quite unlikely in practice.

The fix should be to increase to buf[512+7] and remove the skipCopy optimisation.
